In [4]:
import numpy as np
import pandas as pd

In [2]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])


Vector-vector multiplication (dot product)

Remember, in NumPy u * v multiplies elements element-wise

In [ ]:
u * v  #element-wise multiplication

array([ 2,  0,  0, 12])

In [8]:
u.shape[0]

4

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]  #Assert tests whether a specific condition is True

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [10]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [ ]:
u.dot(v) #dot product in Numpy

np.int64(14)

Matirx-vector multiplication

In [13]:
U = np.array([
  [2, 4, 5, 6],
  [1, 2, 1, 2],
  [3, 1, 2, 1],
])
U.shape

(3, 4)

In [14]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    result = 0.0
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] =  vector_vector_multiplication(U[i],v)
    return result

In [15]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [16]:
U.dot(v)

array([14,  5,  5])

Matrix-matrix multiplication 

In [17]:
V = np.array([
     [1, 1, 2],
     [0, 0.5, 1], 
     [0, 2, 1],
     [2, 1, 0],
 ])

In [19]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows,num_cols))
    for i in range(num_cols):
        Uvi= matrix_vector_multiplication(U,V[:, i])
        result[:,i]= Uvi

    return result

In [20]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [22]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity matrix: using np.eye function

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
V.dot(np.eye(3))

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Inverse matrix

In [ ]:
Vs = V[[0,1,2]] #take the first three rows of the matrix V
Vs
Vs2= V[:,[0,1]]  #take the first two columns of the matrix V
Vs2

array([[1. , 1. ],
       [0. , 0.5],
       [0. , 2. ],
       [2. , 1. ]])

In [31]:
np.linalg.inv(Vs)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])