In [3]:
import numpy as np

One-deminentional arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a= np.array([1,2,3,5,7,12])

In [10]:
a[2]

np.int64(3)

In [11]:
a[2]=10 
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi-dementional arrays

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])  #index starts from 0
n[0,1]  #access one element
n[0]  #access row 1


array([1, 2, 3])

In [ ]:
n[:,0] #access all the rows and just column one
n[:]  #all of the columns and rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Rndomly generate arrays

In [ ]:
np.random.seed(10)  #preduce the same number random 
np.random.rand(5,2)  #generate a random array with 5 rows and 2 columns sample from Uniform distribution

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [29]:
np.random.seed(10)  #preduce the same number random 
np.random.randn(5,2)  #generate a random array with 5 rows and 2 columns sample from Standard Normal

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [30]:
np.random.seed(10)  #preduce the same number random 
100*np.random.rand(5,2)  #generate a random array from 0 to 100 with 5 rows and 2 columns

array([[77.13206433,  2.07519494],
       [63.36482349, 74.88038825],
       [49.85070123, 22.47966455],
       [19.80628648, 76.05307122],
       [16.91108366,  8.83398142]])

In [ ]:
np.random.seed(10)  #preduce the same number random 
np.random.randint(low=0, high=100, size=(5,2))  #generate a random array of integers with 5 rows and 2 columns

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

Elemnt-wise Operations

In [32]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 1  #Adding 1 to all of the elements instead of for loop
a * 2 
a /100


array([1, 2, 3, 4, 5])

In [ ]:
b = (10 + (a * 2)) ** 2  #chain the operations, ** is for power
b

array([100, 144, 196, 256, 324])

In [ ]:
a + b
a / b
a * b

array([100, 145, 198, 259, 328])

Comparison operations

In [ ]:
a >= 2  #the result is boolean

array([False, False,  True,  True,  True])

In [40]:
a > b

array([False, False, False, False, False])

In [ ]:
a [a < b]  #return all of the elements that the condition is true

array([0, 1, 2, 3, 4])

Summarizing operations

In [43]:
a.min()

np.int64(0)

In [44]:
a.max()

np.int64(4)

In [45]:
a.sum()

np.int64(10)

In [46]:
a.mean()

np.float64(2.0)

In [47]:
a.std()

np.float64(1.4142135623730951)